### PR TITLE
Update to latest reason syntax

### PR DESCRIPTION
**Pull request by voxtex**
Accidentally called it latest react syntax meant to say latest reason syntax.

All this does is update to latest reason syntax and remove some unnecessary code. I also added the css requires into the modules so you get the styles for free.

### CODE REVIEW

**Comment by voxtex** [comment]
Decided against including the styles for now as not all modules have styles and child modules need to be excluded.

**Comment by tiensonqin** [comment]
@voxtex Thanks!
Btw, do you want to be the maintainer of this repo?
I'd like to add you to the collaborators if so.

**Comment by voxtex** [comment]
I am willing to try but I am unfamiliar with clojurescript and only hacking my way through right now. If I can get styles working and the improved object creation syntax (to avoid sending undefined to ant-design props) then I think the repo will be in a good place.

**Comment by tiensonqin** [comment]
Cool, looking forward to it!
I don't have too much time to play with reasonml as now, definitely will back.
Anyway, I'll give you access.

**Pull request merged**
